openapi: 3.0.0
info:
  title: Coronatime API
  version: 0.0.1

servers:
  - url: https://coronatime-api.tazo.redberryinternship.ge/api
    description: production server

paths:
  /login:
    post:
      summary: Login.
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: tazo
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: User logged in successfully!!!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: success
                    message:
                      type: string
                      example: User logged in successfully!!!
                    user:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        email:
                          type: string
                          example: tazo@gmail.com
                        username:
                          type: string
                          example: tazo
                        email_verified_at:
                          type: string
                          example: 2022-02-23T20:31:49.000000Z
                        email_verified_token:
                          type: string
                          example: 7DVOxRaWScjptofxSTI9NQyeqnsi6I9SnTpqbAHVChyqJFcQl3EBtzhore2h
                        created_at:
                          type: string
                          example: 2022-02-23T17:05:28.000000Z
                        updated_at:
                          type: string
                          example: 2022-02-23T17:05:28.000000Z
                    idToken:
                      type: string
                      example: Y2hoeHRuSldKdVU5YlNyZVBBRmdsR055c3piTnNocVhuRTlIVFpKUg
  /signup:
    post:
      summary: Signup.
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: gendalf
                email:
                  type: string
                  example: gendalf@gmail.com
                password:
                  type: string
                  example: gendalf123
      responses:
        '200':
          description: User singup successfully!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: success
                    message:
                      type: string
                      example: Welcome to coronatime!!!
  /reset-password-confirm:
    post:
      summary: Email confirm.
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: gendalf@gmail.com
      responses:
        '200':
          description: Confirmation email send success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: success
                    message:
                      type: string
                      example: We have sent you a confirmation email
  /reset-password:
    post:
      summary: Resset password.
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: Y2hoeHRuSldKdVU5YlNyZVBBRmdsR055c3piTnNocVhuRTlIVFpKUg
                password:
                  type: string
                  example: exsample_password
      responses:
        '200':
          description: Password updated!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: success
                    message:
                      type: string
                      example: Password successfully updated!
  /countries:
    get:
      summary: Returns countries statistics.
      responses:
        '200': # status code
          description: A JSON array
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 1
                    code:
                      type: string
                      example: "GE"
                    country:
                      type: object
                      properties:
                        en:
                          type: string
                          example: Georgia
                        ge:
                          type: string
                          example: საქართველო
                    confirmed:
                      type: string
                      example: "2614"
                    recovered:
                      type: string
                      example: "3611"
                    critical:
                      type: string
                      example: "3687"
                    deaths:
                      type: string
                      example: "921"
                    created_at:
                      type: string
                      example: "2022-02-22T09:22:36.000000Z"
                    updated_at:
                      type: string
                      example: "2022-02-22T09:22:36.000000Z"
